version: '2'

services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: mypass

  web:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - './:/opt/app'
    environment:
      RAILS_ENV: development
      POSTGRES_PASSWORD: mypass
    depends_on:
      - db
    tty: true
    stdin_open: true

  test:
    command: rspec
    build: .
    volumes:
      - './:/opt/app'
    environment:
      RAILS_ENV: test
      POSTGRES_PASSWORD: mypass
    depends_on:
      - db
    tty: true
    stdin_open: true